/**
 * Resource metadata unit tests — Phase 5-4A-TD.
 *
 * Validates the structure of ResourceMetadata objects
 * as generated by the import handler. No file I/O required.
 */
import { describe, it, expect } from 'vitest';

// Build a mock metadata object matching the import handler's output
function buildMockMetadata(overrides: Record<string, unknown> = {}) {
  return {
    schemaVersion: 1,
    resourceId: 'res_mock_12345',
    vaultId: 'test-vault',
    resourceRelativePath: 'resources/pdf/paper.pdf',
    metadataRelativePath: '.schola/metadata/resources/res_mock_12345.json',
    kind: 'pdf',
    originalName: 'paper.pdf',
    size: 102400,
    importedAt: 1700000000000,
    source: 'imported' as const,
    ...overrides,
  };
}

// ── Core fields ───────────────────────────────────

describe('ResourceMetadata — core fields', () => {
  it('schemaVersion === 1', () => {
    const m = buildMockMetadata();
    expect(m.schemaVersion).toBe(1);
  });

  it('resourceId exists and is string', () => {
    const m = buildMockMetadata();
    expect(typeof m.resourceId).toBe('string');
    expect(m.resourceId.length).toBeGreaterThan(0);
  });

  it('vaultId exists and is string', () => {
    const m = buildMockMetadata();
    expect(typeof m.vaultId).toBe('string');
    expect(m.vaultId.length).toBeGreaterThan(0);
  });

  it('resourceRelativePath is vault-relative', () => {
    const m = buildMockMetadata();
    expect(m.resourceRelativePath).not.toContain(':\\');
    expect(m.resourceRelativePath).not.toContain('/home/');
    expect(m.resourceRelativePath).not.toContain('/Users/');
    expect(m.resourceRelativePath.startsWith('resources/')).toBe(true);
  });

  it('metadataRelativePath is vault-relative', () => {
    const m = buildMockMetadata();
    expect(m.metadataRelativePath).not.toContain(':\\');
    expect(m.metadataRelativePath).not.toContain('/home/');
    expect(m.metadataRelativePath.startsWith('.schola/metadata/resources/')).toBe(true);
  });

  it('kind is valid', () => {
    const validKinds = ['pdf', 'html', 'docx', 'pptx', 'xlsx', 'csv', 'txt', 'image', 'other', 'markdown'];
    const m = buildMockMetadata({ kind: 'pdf' });
    expect(validKinds).toContain(m.kind);
  });

  it('originalName matches expected', () => {
    const m = buildMockMetadata({ originalName: 'paper.pdf' });
    expect(m.originalName).toBe('paper.pdf');
  });

  it('size is number > 0', () => {
    const m = buildMockMetadata();
    expect(typeof m.size).toBe('number');
    expect(m.size).toBeGreaterThan(0);
  });

  it('importedAt is number (timestamp)', () => {
    const m = buildMockMetadata();
    expect(typeof m.importedAt).toBe('number');
    expect(m.importedAt).toBeGreaterThan(1600000000000); // After 2020
  });

  it('source === imported', () => {
    const m = buildMockMetadata();
    expect(m.source).toBe('imported');
  });
});

// ── Absence of forbidden fields ───────────────────

describe('ResourceMetadata — no forbidden fields', () => {
  it('no absolutePath', () => {
    const m = buildMockMetadata();
    expect('absolutePath' in m).toBe(false);
  });

  it('no systemPath', () => {
    const m = buildMockMetadata();
    expect('systemPath' in m).toBe(false);
  });

  it('no nativePath', () => {
    const m = buildMockMetadata();
    expect('nativePath' in m).toBe(false);
  });

  it('no fileUrl', () => {
    const m = buildMockMetadata();
    expect('fileUrl' in m).toBe(false);
  });

  it('no sourcePath', () => {
    const m = buildMockMetadata();
    expect('sourcePath' in m).toBe(false);
  });

  it('no content field', () => {
    const m = buildMockMetadata();
    expect('content' in m).toBe(false);
  });

  it('no body field', () => {
    const m = buildMockMetadata();
    expect('body' in m).toBe(false);
  });

  it('no buffer field', () => {
    const m = buildMockMetadata();
    expect('buffer' in m).toBe(false);
  });

  it('no secret field', () => {
    const m = buildMockMetadata();
    expect('secret' in m).toBe(false);
  });

  it('no key field', () => {
    const m = buildMockMetadata();
    expect('key' in m).toBe(false);
  });

  it('no token field', () => {
    const m = buildMockMetadata();
    expect('token' in m).toBe(false);
  });

  it('no apiKey field', () => {
    const m = buildMockMetadata();
    expect('apiKey' in m).toBe(false);
  });
});

// ── Path safety ───────────────────────────────────

describe('ResourceMetadata — path safety', () => {
  it('resourceRelativePath has no system absolute path pattern', () => {
    const m = buildMockMetadata({ resourceRelativePath: 'resources/pdf/paper.pdf' });
    expect(m.resourceRelativePath).not.toContain(':\\');
    expect(m.resourceRelativePath).not.toContain('/home/');
    expect(m.resourceRelativePath).not.toContain('/Users/');
    expect(m.resourceRelativePath).not.toContain('C:');
  });

  it('metadataRelativePath has no system absolute path pattern', () => {
    const m = buildMockMetadata({ metadataRelativePath: '.schola/metadata/resources/res_abc.json' });
    expect(m.metadataRelativePath).not.toContain(':\\');
    expect(m.metadataRelativePath).not.toContain('/home/');
    expect(m.metadataRelativePath).not.toContain('/Users/');
    expect(m.metadataRelativePath).not.toContain('C:');
  });
});

// ── Different resource kinds ──────────────────────

describe('ResourceMetadata — resource kind coverage', () => {
  it('pdf resource', () => {
    const m = buildMockMetadata({
      kind: 'pdf',
      resourceRelativePath: 'resources/pdf/paper.pdf',
    });
    expect(m.kind).toBe('pdf');
    expect(m.resourceRelativePath).toContain('resources/pdf/');
  });

  it('html resource', () => {
    const m = buildMockMetadata({
      kind: 'html',
      resourceRelativePath: 'resources/html/page.html',
    });
    expect(m.kind).toBe('html');
    expect(m.resourceRelativePath).toContain('resources/html/');
  });

  it('docx resource', () => {
    const m = buildMockMetadata({
      kind: 'docx',
      resourceRelativePath: 'resources/docx/report.docx',
    });
    expect(m.kind).toBe('docx');
  });

  it('image resource', () => {
    const m = buildMockMetadata({
      kind: 'image',
      resourceRelativePath: 'resources/images/photo.png',
    });
    expect(m.kind).toBe('image');
  });

  it('csv resource', () => {
    const m = buildMockMetadata({
      kind: 'csv',
      resourceRelativePath: 'resources/csv/data.csv',
    });
    expect(m.kind).toBe('csv');
  });

  it('other resource', () => {
    const m = buildMockMetadata({
      kind: 'other',
      resourceRelativePath: 'resources/other/file.bin',
    });
    expect(m.kind).toBe('other');
  });

  it('markdown resource (unusual but valid)', () => {
    const m = buildMockMetadata({
      kind: 'markdown',
      resourceRelativePath: 'notes/readme.md',
    });
    expect(m.kind).toBe('markdown');
    expect(m.resourceRelativePath).toContain('notes/');
  });
});
